### ISSUE TITLE
Is this "null" value important?

### ISSUE THREAD

**Issue by gcapes** [RoryAtBar/Abaqus_bayesian_matflow#29]
Hi @RoryAtBar 

I'm refactoring the data setup code, and noticed that for force, you append a list containing zero `[0]`
https://github.com/RoryAtBar/Abaqus_bayesian_matflow/blob/matflow/data_set_up/parallel_core_pymc/Data_set_up.py#L137

whereas for the other data profiles, you just append an empty list e.g.
https://github.com/RoryAtBar/Abaqus_bayesian_matflow/blob/matflow/data_set_up/parallel_core_pymc/Data_set_up.py#L107

It it important which is used? Would be slightly easier if we could use the same value in each case.

**Comment by RoryAtBar** [comment]
For force the list containing zero, the reason is simply that if the simulation failed, then for that entry an rpt file may not have been generated. If that happened, I needed something in place in the array for that entry so that if I wanted to plot all of the force vs. timestep values as a cursory way to check the overall results are reasonable, which doesn't cause an error while plotting.

In the case of force, the total value for force is set 1 plus set 2. The zero is just there so there is a number to add

**Comment by gcapes** [comment]
Thanks Rory. I can of course replicate the behaviour of the original script, but would it cause a problem if we add a list containing zero for all the data rather than just the force data?

**Comment by RoryAtBar** [comment]
I can't think of any reason it would cause problems...

**Comment by gcapes** [comment]
Thanks. In fact, on closer inspection of the code, it's only the force values which are used (`temp`, `peeq`, and `barelling` profiles are calculated but never used), so it definitely doesn't matter :smile:

**Comment by RoryAtBar** [comment]
It would be useful to store the other values somewhere though as they are quite useful in other kinds of analysis...

**Comment by gcapes** [comment]
Ok I'll put their calculation back in in readiness for future work :)

**Comment by RoryAtBar** [comment]
Thanks!
